Creation of models Admin and Service
gastonvalles/YouPet pull request #2
Opened 2022-11-23 21:54 UTC by FedeSaffores

2022-11-23 22:18 UTC, gastonvalles submitted a review, later dismissed

2022-11-24 01:51 UTC, gastonvalles requested changes
createdAt y updatedAt deberian ser false
en Service, price y average deberian ser integer

2022-11-24 20:00 UTC, ernestovv85 approved these changes

2022-11-24 20:09 UTC, gastonvalles approved these changes

2022-11-24 20:09 UTC, Klevens approved these changes

2022-11-24 20:09 UTC, merged