Creation of Score and Vet models
gastonvalles/YouPet pull request #3
Opened 2022-11-23 23:38 UTC by Klevens

Hey 👋, I want to merge this changes

2022-11-23 23:44 UTC, gastonvalles approved these changes, later dismissed

2022-11-24 01:49 UTC, gastonvalles requested changes
createdAt y updatedAt deberian ser false en vez de null
el datatypes de average deberia ser integer

2022-11-24 02:10 UTC, Klevens commented
Done

2022-11-24 15:20 UTC, gastonvalles approved these changes

2022-11-24 19:52 UTC, vemodi approved these changes

2022-11-24 20:00 UTC, ernestovv85 approved these changes

2022-11-24 20:02 UTC, merged